######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 00:03:28 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qimageconv.h
SOURCES += qimageconv.cpp
