######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 30 00:03:28 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++0x

# Input
HEADERS += qimageconv.h \
    convolution2d.h \
    TimeLog.h \
    QImageArrayAdaptor.h \
    QTableWidgetKernelHelper.h
SOURCES += qimageconv.cpp
